on:
  push:
    branches:
    - master
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: razorpagesmovies-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20240725105715
  RESOURCE_GROUP: dataBaseProjects
  CONTAINER_REGISTRY_NAME: registry20240725110058
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20240725110058.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.managedEnv20240725105715_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.registry20240725110058_USERNAME_77FF }}
        acrPassword: ${{ secrets.registry20240725110058_PASSWORD_77FF }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
